# Generated by Django 5.0.6 on 2024-05-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_score_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(default='<django.db.models.fields.AutoField>_ph.jpg', max_length=255),
        ),
    ]
