# Generated by Django 5.0.6 on 2024-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
