# Generated by Django 5.0.6 on 2024-05-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_model_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='status',
            field=models.CharField(choices=[('pending', '审核中'), ('training', '训练中'), ('completed', '已完成')], default='pending', max_length=10),
        ),
    ]
